name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - run: g++ --version
    - run: gem install anomaly_detection
